### ISSUE TITLE
Shameless plug: place-modifiers, a very very similar project

### ISSUE THREAD

**Issue by Hexstream** [porky11/setf-everything#1]
Hello, I hope this won't be seen as too spammy but you might want to look into my "place-modifiers" library, which is extremely similar in concept. It's in quicklisp.

http://www.hexstreamsoft.com/libraries/place-modifiers/

(I would have sent an email instead, but none is indicated on your profile.)

Hope this helps.

**Comment by mrkkrp** [comment]
How about [trivial-update](https://github.com/mrkkrp/trivial-update) too? :-D

**Comment by Hexstream** [comment]
Well... if I may:

With place-modifiers you should theoretically be able to do `(modify (funcall function my-place))`, although due to a trivial bug you would currently have to write `(modify (funcall function (:place my-place)))` instead.

(And of course, if `my-function` is just a built-in function, you should be able to write just `(modify (function my-place))`, which is much more elegant.)

(The fix for the bug would simply be replacing `(funcall nil (2 -1 1))` at https://github.com/Hexstream/place-modifiers/blob/master/definitions.lisp#L25 with `(funcall t (2 -1 1))`, signifying that `funcall` is an "inconceivable place".)

I previously had a not very elegant system for selecting among "variants" (besides the "primary variant"), choosing which argument should be treated as the place, although I just realized that you should be able to wrap any of the arguments in the `:place` "local special form" to choose what I call the "spot" (which would then be mostly an obsoleted concept)...

The documentation should also mention all the available place-modifiers instead of having to consult https://github.com/Hexstream/place-modifiers/blob/master/definitions.lisp directly...

---

**So, I'll probably release an update to place-modifiers soon.**
I think it would be about time I dusted off that perhaps underrated project. :)

(Sorry if this isn't an easily comprehensible rambling, but using the library itself is pretty straightforward (I hope), and will be especially so after I make my update.)

**Comment by Hexstream** [comment]
Sorry, I find myself [unable to finish the place-modifiers update anytime soon](https://twitter.com/HexstreamSoft/status/685640445133754368) (it will probably take years), even though [the bulk of the work is already done](https://github.com/Hexstream/place-modifiers/commit/ef54744713d930316e0d0fa498b796ff8a65d2b8).

Sorry about this, I guess I'll close this now.

**Comment by porky11** [comment]
you don't have to apologize, i only wasn't online in github for some time
your project seems more complex than what i wrote,
i only added setf for default functions and special forms, so they can be used as normal lisp-functions.
I'll look at your project a bit more, maybe it's better
